name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set environment variables
        env:
          SPRING_DATASOURCE_NAME: ${{ secrets.SPRING_DATASOURCE_NAME }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          BUCKETNAME: ${{ secrets.BUCKETNAME }}
          S3ACCESSKEY: ${{ secrets.S3ACCESSKEY }}
          S3SECRETKEY: ${{ secrets.S3SECRETKEY }}
          REGION: ${{ secrets.REGION }}
        run: echo "Environment variables set"

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run application
        env:
          SPRING_DATASOURCE_NAME: ${{ secrets.SPRING_DATASOURCE_NAME }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          BUCKETNAME: ${{ secrets.BUCKETNAME }}
          S3ACCESSKEY: ${{ secrets.S3ACCESSKEY }}
          S3SECRETKEY: ${{ secrets.S3SECRETKEY }}
          REGION: ${{ secrets.REGION }}
        run: java -jar build/libs/rockcafe-0.0.1-SNAPSHOT.jar