name: Build and Test Spring Boot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Java 17 설치 (Temurin 배포판 사용)
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 3. Gradlew 실행 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      # 5. Gradle 테스트 실행
      - name: Run tests with Gradle
        run: ./gradlew test
        shell: bash
